window:
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 6
    y: 6
scrolling:
  # Specifying '0' will disable scrolling.
  history: 100000
  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3
font:
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  size: 16.0
  use_thin_strokes: true
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true
schemes:
  gruvbox_dark_base16: &gruvbox_dark_base16
    primary:
      background: '#1d2021'
      foreground: '#d5c4a1'
    cursor:
      text: '#1d2021'
      cursor: '#d5c4a1'
    normal:
      black:   '#1d2021'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#d5c4a1'
    bright:
      black:   '#665c54'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#fbf1c7'
    indexed_colors:
    - { index: 16, color: '#fe8019' }
    - { index: 17, color: '#d65d0e' }
    - { index: 18, color: '#3c3836' }
    - { index: 19, color: '#504945' }
    - { index: 20, color: '#bdae93' }
    - { index: 21, color: '#ebdbb2' }

# Nord Theme Colors
# https://github.com/arcticicestudio/nord-alacritty/blob/develop/src/nord.yml
  nord_dark: &nord_dark
    primary:
      background: '#2e3440'
      foreground: '#d8dee9'
      dim_foreground: '#a5abb6'
    cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    vi_mode_cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    selection:
      text: CellForeground
      background: '#4c566a'
    search:
      matches:
        foreground: CellBackground
        background: '#88c0d0'
      bar:
        background: '#434c5e'
        foreground: '#d8dee9'
    normal:
      black: '#3b4252'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#88c0d0'
      white: '#e5e9f0'
    bright:
      black: '#4c566a'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#8fbcbb'
      white: '#eceff4'
    dim:
      black: '#373e4d'
      red: '#94545d'
      green: '#809575'
      yellow: '#b29e75'
      blue: '#68809a'
      magenta: '#8c738c'
      cyan: '#6d96a5'
      white: '#aeb3bb'
colors: *nord_dark
# Specifying a `duration` of `0` will disable the visual bell.
bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'
window.opacity: 1.00
selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true
# Login shell with arguments
shell:
  program: /bin/zsh
  args:
    - --login
# Allow terminal applications to change Alacritty’s window title.
window.dynamic_title: true
cursor:
  style: Block
  unfocused_hollow: true
# Live config reload (changes require restart)
live_config_reload: true

debug:
  # Display the time it takes to redraw each frame.
  render_timer: false

  # Keep the log file after quitting Alacritty.
  persistent_logging: false

  # Log level
  #
  # Values for `log_level`:
  #   - None
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  log_level: Warn

  # Print all received window events.
  print_events: false

  # Record all characters and escape sequences as test data.
  ref_test: false

key_bindings:
  - { key: F,  mods: Alt, chars: "\x1bf" }
  - { key: B,  mods: Alt, chars: "\x1bb" }
  - { key: H,  mods: Alt, chars: "\x1bh" }
  - { key: J,  mods: Alt, chars: "\x1bj" }
  - { key: K,  mods: Alt, chars: "\x1bk" }
  - { key: L,  mods: Alt, chars: "\x1bl" }

